### ISSUE TITLE
Issue With PluginYML

### ISSUE THREAD

**Issue by cjburkey01** [ThunderGemios10/Survival-Games#3]
I got an issue with the plugin.yml when running:

```
[20:42:28] [Server thread/ERROR]: Could not load 'plugins/Survival-Games.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:164) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 1, column 1:
    name: SurvivalGames
    ^
expected <block end>, but found FlowEntry
 in 'reader', line 4, column 27:
    authors: [Double0negative], ThunderGemios10
                              ^

    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:381) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:232) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    ... 5 more
```

**Comment by cjburkey01** [comment]
It looks fixed in the code, so a new release should fix it.

**Comment by ThunderGemios10** [comment]
All right. I'll release a latest.

**Comment by cjburkey01** [comment]
Thank you :)

**Comment by ThunderGemios10** [comment]
Ok, I just updated the first release with the new jar. It should load properly now..
