### ISSUE TITLE
Error occurred while disabling SurvivalGames v0.6.3.2 (Is it up to date?)

### ISSUE THREAD

**Issue by kefaquin** [ThunderGemios10/Survival-Games#33]
[20:04:13] [Server thread/INFO]: [SurvivalGames] Disabling SurvivalGames v0.6.3.2
[20:04:13] [Server thread/ERROR]: Error occurred while disabling SurvivalGames v0.6.3.2 (Is it up to date?)
java.lang.NullPointerException
	at org.mcsg.survivalgames.SettingsManager.saveSpawns(SettingsManager.java:231) ~[?:?]
	at org.mcsg.survivalgames.SurvivalGames.onDisable(SurvivalGames.java:46) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:335) [Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:441) [Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:572) [Playboxone.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[20:04:13] [Server thread/INFO]: [ArrowTeleport] Disabling ArrowTeleport v1.4
[20:04:13] [Server thread/INFO]: ArrowTeleport has been unloaded successfully!

**Comment by ThunderGemios10** [comment]
@kefaquin What Bukkit version are you using?
