### ISSUE TITLE
Chest.yml Doesn't Accept New Names

### ISSUE THREAD

**Issue by cjburkey01** [ThunderGemios10/Survival-Games#42]
I see from the config file, it explains that the format may be any of the following: 
```
<itemid>,<max amount per slot>[,<DV>[,<enchantment>:<level> ...[,<name>]]]
diamond_sword,1
236,1
diamond_sword,1,0,sharpness:5 knockback:2,Excalibur
Lapis Lazuli
351,1,4
```
However, it appears that using `diamond_sword` or any other name, like `gold_ore` return this error:
```
[15:22:04 WARN]: [SurvivalGames] Task #497600 for SurvivalGames v0.6.6 generated an exception
java.lang.NumberFormatException: For input string: "Wooden Sword"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_131]
	at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:83) ~[?:?]
	at com.thundergemios10.survivalgames.util.ChestRatioStorage.setup(ChestRatioStorage.java:41) ~[?:?]
	at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:92) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
Has this been implemented yet, or am I doing something wrong?

**Comment by ThunderGemios10** [comment]
@cjburkey01 I don't think i have implemented that yet.

Please read #24
