### ISSUE TITLE
The problem with disconnecting during the countdown!!!

### ISSUE THREAD

**Issue by McJoker123** [ThunderGemios10/Survival-Games#59]
If you go into the game in doubles then someone threw it out during the countdown before the start of the game! Or he went out forcibly! Then Arena breaks down writes that it is busy and besides reload nothing helps! How can I fix this problem?

**Comment by ThunderGemios10** [comment]
@McJoker123 Can you please send me error logs from your console when this happened?

**Comment by McJoker123** [comment]
[12:23:47] [Server thread/INFO]: [SurvivalGames] ???????????????????????
[12:23:47] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[12:23:47] [Server thread/WARN]: 	at java.util.ArrayList.rangeCheck(Unknown Source)
[12:23:47] [Server thread/WARN]: 	at java.util.ArrayList.get(Unknown Source)
[12:23:47] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.Game.playerWin(Game.java:667)
[12:23:47] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.Game.killPlayer(Game.java:637)
[12:23:47] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.events.LogoutEvent.PlayerLoggout(LogoutEvent.java:24)
[12:23:47] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:23:47] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:23:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:23:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:23:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
[12:23:47] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:23:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[12:23:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:383)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1068)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:309)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(SourceFile:215)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:768)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651)
[12:23:47] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555)
[12:23:47] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:23:47] [Server thread/INFO]: [SurvivalGames] ID1
[12:23:47] [Server thread/INFO]: [SurvivalGames] true
[12:23:47] [Server thread/INFO]: [SurvivalGames] 0
[12:23:47] [Server thread/INFO]: [SurvivalGames] []
[12:23:47] [Server thread/INFO]: [SurvivalGames] Test
[12:23:47] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to SurvivalGames v0.6.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:383) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1068) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:309) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(SourceFile:215) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:768) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.thundergemios10.survivalgames.Game.killPlayer(Game.java:650) ~[?:?]
	at com.thundergemios10.survivalgames.events.LogoutEvent.PlayerLoggout(LogoutEvent.java:24) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-809c399]
	... 12 more
[12:23:47] [Server thread/INFO]: Test left the game
[12:23:49] [Netty Server IO #5/INFO]: [0;36;22m?  [0;30;1m[Игрок][0;32;1m ExtremeNordic [0;31;22m? [0;37;22m[3m: [0;37;1m[3mсколько времяни можно стоять в афк?[m @

**Comment by McJoker123** [comment]
At the time of counting out 1 player! The game continues to start, if the game was in doubles then naturally it can not find another player and goes out too, so it throws it into the dead and the arena of kagba hangs on the plate lit 0/1/4 For example!

**Comment by ThunderGemios10** [comment]
@McJoker123 Pushed a fix for the issue. Should be resolved now.
