### ISSUE TITLE
The previous error with the countdown was not corrected!

### ISSUE THREAD

**Issue by McJoker123** [ThunderGemios10/Survival-Games#60]
I saw you fixed the error with the exit during the countdown! But now there was one more, at this time when the remaining player is kicking from the arena, if he enters back, then the countdown starts immediately after which the pool is given! And He again remains to fight with himself! Comes from the arena, and the arena again hangs! on the second tab icon 0/1/4! ! HELP ME PLEASE!

[01:44:53] [Server thread/INFO]: [SurvivalGames] ???????????????????????
[01:44:53] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[01:44:53] [Server thread/WARN]: at java.util.ArrayList.rangeCheck(Unknown Source)
[01:44:53] [Server thread/WARN]: at java.util.ArrayList.get(Unknown Source)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.Game.playerWin(Game.java:668)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.Game.killPlayer(Game.java:638)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.Game.removePlayer(Game.java:528)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.GameManager.removePlayer(GameManager.java:194)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.commands.Leave.onCommand(Leave.java:17)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.CommandHandler.onCommand(CommandHandler.java:155)
[01:44:53] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:44:53] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:44:53] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[01:44:53] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:44:53] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[01:44:53] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)
[01:44:53] [Server thread/INFO]: [SurvivalGames] ID1
[01:44:53] [Server thread/INFO]: [SurvivalGames] false
[01:44:53] [Server thread/INFO]: [SurvivalGames] 0
[01:44:53] [Server thread/INFO]: [SurvivalGames] []
[01:44:53] [Server thread/INFO]: [SurvivalGames] hype_producer
[01:44:53] [Server thread/WARN]: java.lang.NullPointerException
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.Game.killPlayer(Game.java:651)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.Game.removePlayer(Game.java:528)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.GameManager.removePlayer(GameManager.java:194)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.commands.Leave.onCommand(Leave.java:17)
[01:44:53] [Server thread/WARN]: at com.thundergemios10.survivalgames.CommandHandler.onCommand(CommandHandler.java:155)
[01:44:53] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:44:53] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:44:53] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[01:44:53] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:44:53] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[01:44:53] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[01:44:53] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by ThunderGemios10** [comment]
@McJoker123 What do you mean when the player is "kicking" off the arena?

**Comment by McJoker123** [comment]
If the player leaves the game during the countdown, the second player throws out of the arena, if the second player will go back to the arena immediately, the count starts immediately without waiting for the players! In other words, the player began to throw out if one out of the game is a plus, the arena is still not stopping , if the player is thrown from the arena and the fact that the opponent came out, comes about

**Comment by McJoker123** [comment]
Would you like a video so I can understand?
