### ISSUE TITLE
NullPointerException when starting server

### ISSUE THREAD

**Issue by MCUmbrella** [ThunderGemios10/Survival-Games#86]
**Describe the bug**
Every time I start the server it generate an NullPointerException. I have not tested further whether this issue affects the gaming experience.

**To Reproduce**
Start the server

**Expected behavior**
No problem when starting server

**Screenshots**
No screenshots

**Errors**
`[21:10:23] [Server thread/WARN]: [SurvivalGames] Task #13 for SurvivalGames v0.7.5 generated an exception
java.lang.NullPointerException: null
    at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:50) ~[patched_1.12.2.jar:git-Paper-1618]
    at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:98) ~[?:?]
    at com.thundergemios10.survivalgames.util.ChestRatioStorage.setup(ChestRatioStorage.java:41) ~[?:?]
    at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:118) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]`

**Specfiy which versions your using**
 - Plugin version: SurvivalGames v0.7.5
 - Spigot version: Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 - WorldEdit version: v6.1.9;caf0ad9

**Additional context**
Full latest.log file: https://pastebin.com/PeUpBeJM

**Comment by Remyk1** [comment]
You probably have a invalid Material name in one your config files(chest.yml, config.yml and/or kits.yml)

**Comment by Remyk1** [comment]
I should add beter error messaging to this system
