### ISSUE TITLE
Game not starting, task #26 generated an exception

### ISSUE THREAD

**Issue by Gorbiel** [ThunderGemios10/Survival-Games#88]
**Describe the bug**
When clicking on sign nothing happens and I can break arena blocks

**Errors**
 [SurvivalGames] Task #26 for SurvivalGames v0.7.5 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:131) ~[?:?]
        at com.thundergemios10.survivalgames.util.ChestRatioStorage.setup(ChestRatioStorage.java:41) ~[?:?]
        at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-132]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-132]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-132]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-132]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-132]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Specfiy which versions your using**
 - Plugin version - v0.7.5
 - Paper #132 for MC 1.15.2
 - WorldEdit version - v7.1.0

**Additional context**
It started after changing the config (I attached all config files and server log)
[latest.log](https://github.com/ThunderGemios10/Survival-Games/files/4335264/latest.log)
[configs.zip](https://github.com/ThunderGemios10/Survival-Games/files/4335271/configs.zip)

**Comment by Remyk1** [comment]
Could you enable debugging in config.yml

**Comment by Gorbiel** [comment]
I fixed it by deleting all items in chest config with custom tags, apparently one of them was causing this. But now I don't know how to add enchanted books and paper with custom name, can you help me?

**Comment by Remyk1** [comment]
Sure, the format is \<itemid\>,\<max amount per slot\>[,\<DV\>[,\<enchantment\>:\<level\> ...[,\<name\>]]]
so for paper with custom name it would be ``'PAPER, 1, 0, none, custom name'``.
For the enchanted books you could try ``'ENCHANTED_BOOK, 1, 0, sharpness:1, custom name'``, not sure if this will work though because it won't apply it as if it is a book but like a sword or armor piece.

**Comment by Gorbiel** [comment]
Ok, I'll try. Thanks for help!
