### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by LokiTheGod123** [ThunderGemios10/Survival-Games#99]
My chests don't refill, I can break blocks and I can leave my spawnpoint before the game starts! Console: [18:37:58] [Server thread/WARN]: [SurvivalGames] [Warning] [ItemReader] Could not parse material: "WOOD_DOOR"
[18:37:58] [Server thread/WARN]: java.lang.IllegalArgumentException: Material cannot be null
[18:37:58] [Server thread/WARN]: at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[18:37:58] [Server thread/WARN]: at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:82)
[18:37:58] [Server thread/WARN]: at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:70)
[18:37:58] [Server thread/WARN]: at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:58)
[18:37:58] [Server thread/WARN]: at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:44)
[18:37:58] [Server thread/WARN]: at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:100)
[18:37:58] [Server thread/WARN]: at com.thundergemios10.survivalgames.util.Kit.load(Kit.java:33)
[18:37:58] [Server thread/WARN]: at com.thundergemios10.survivalgames.util.Kit.<init>(Kit.java:25)
[18:37:58] [Server thread/WARN]: at com.thundergemios10.survivalgames.GameManager.LoadKits(GameManager.java:71)
[18:37:58] [Server thread/WARN]: at com.thundergemios10.survivalgames.GameManager.setup(GameManager.java:53)
[18:37:58] [Server thread/WARN]: at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:101)
[18:37:58] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[18:37:58] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[18:37:58] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[18:37:58] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[18:37:58] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[18:37:58] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[18:37:58] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:830)
[18:37:58] [Server thread/WARN]: [SurvivalGames] Task #751455 for SurvivalGames v0.7.5 generated an exception

And my chest file on pastebin: https://pastebin.com/eMxRBUVe

**Comment by Remyk1** [comment]
This is from the kits.yml file 
![image](https://user-images.githubusercontent.com/32412516/92451543-26c85e80-f1bd-11ea-8839-fddfc1ebf9bf.png)
Just change the icon to $(WoodType)_DOOR (e.g OAK_DOOR) if you're on 1.13 or above, if you're on 1.12 WOODEN_DOOR for oak or SPRUCE_DOOR for spruce.
You can of course change the icon to any material you want.

**Comment by LokiTheGod123** [comment]
Now when reloading plugin I got this error in console: [21:20:18] [Server thread/WARN]: [SurvivalGames] Task #212186 for SurvivalGames v0.7.5 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:131) ~[?:?]
at com.thundergemios10.survivalgames.util.ChestRatioStorage.setup(ChestRatioStorage.java:41) ~[?:?]
at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:118) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[mc.jar:git-Spigot-379750e-f26d8e8]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[mc.jar:git-Spigot-379750e-f26d8e8]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[mc.jar:git-Spigot-379750e-f26d8e8]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[mc.jar:git-Spigot-379750e-f26d8e8]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[mc.jar:git-Spigot-379750e-f26d8e8]
Chests don't refill and I can walk when waiting for the games to start.

**Comment by Remyk1** [comment]
Enchantment need to have a level specified, even for infinity and flame so for infinity it would be infinity:1

**Comment by LokiTheGod123** [comment]
Thank you! Also, my players reported that they can't join the game - it says that they don't have the permission. What are the permissions?

**Comment by LokiTheGod123** [comment]
Never mind. I found it. Could you please help me with this error after using /sg join 1? @Remyk1 
`[18:43:27] [Server thread/INFO]: Norbik1004 issued server command: /sg autojoin
[18:43:27] [Server thread/WARN]: java.lang.IllegalArgumentException: location.world
[18:43:27] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[18:43:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.entity.CraftPlayer.teleport(CraftPlayer.java:617)
[18:43:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.entity.CraftEntity.teleport(CraftEntity.java:468)
[18:43:27] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.Game.addPlayer(Game.java:312)
[18:43:27] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.GameManager.addPlayer(GameManager.java:259)
[18:43:27] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.GameManager.autoAddPlayer(GameManager.java:324)
[18:43:27] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.commands.AutoJoin.onCommand(AutoJoin.java:18)
[18:43:27] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.CommandHandler.onCommand(CommandHandler.java:180)
[18:43:27] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:43:27] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[18:43:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
[18:43:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[18:43:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by LokiTheGod123** [comment]
@Remyk1 
Could you please help me?

**Comment by Remyk1** [comment]
Make sure you have done "/sg setlobbyspawn"

**Comment by LokiTheGod123** [comment]
OMG, it works now! Thanks!
